### ISSUE TITLE
Long blocked URLs cause SQL error

### ISSUE THREAD

**Issue by guus-frenken** [zaxbux/oc-securityheaders-plugin#2]
When the blocked URL in a CSP report is longer than the max. allowed length of a varchar (191), it throws the following SQL error:

PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'blocked_uri' at row 1 in /var/www/vhosts/website.tld/httpdocs/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105

This error causes the CSP violation not to be stored in the database.

Possible solution: In the "zaxbux_securityheaders_reporting_csp" database table, change the "blocked_uri" column type from varchar to text.

**Comment by zaxbux** [comment]
Fixed by 5d3b3368a501d37c16733c189f20b167d22a80b2
